### ISSUE TITLE
Return `Result` instead of calling `.expect()` in conversions with `chono::DateTime`

### ISSUE THREAD

**Issue by rjzak** [sorairolake/nt-time#149]
### Checklist

- [X] I have searched the existing issues

### Summary

The calls to `.expect()` in `impl From<FileTime> for chrono::DateTime<chrono::Utc>` makes me nervous, why not use `TryFrom`?

https://github.com/sorairolake/nt-time/blob/398fb74e7472f9f3f7f8d98532a8bdfca2746e18/src/file_time.rs#L1462-L1500

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sorairolake** [comment]
@rjzak Because this conversion is always expected to be successful. Panics should not occur unless there is a bug in the implementation. However, `TimeDelta::try_seconds` may be replaced by `TimeDelta::seconds`.

**Comment by rjzak** [comment]
Ok, I feel better then. I'm trying to build a system for storing and analyzing malware, so I expect to encounter dates which may be nonsense.
Thank you!
