### ISSUE TITLE
Add from low and high DWORD

### ISSUE THREAD

**Issue by russellbanks** [sorairolake/nt-time#250]
### Checklist

- [X] I have searched the existing issues

### Summary

The [`FILETIME`](https://learn.microsoft.com/windows/win32/api/minwinbase/ns-minwinbase-filetime) I'm dealing with is stored as a separate low and high [`DWORD`](https://learn.microsoft.com/openspecs/windows_protocols/ms-dtyp/262627d8-3418-4627-9218-4ffe110850b2) (u32).

Having a `FileTime::from_low_high` (or similarly named) function would be helpful as it saves me from doing `Filetime::new(u64::from(high) << u32::BITS | u64::from(low))`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sorairolake** [comment]
@russellbanks I think the API looks like this:

```rust
fn from_high_low(high: u32, low: u32) -> FileTime

fn to_high_low(self) -> (u32, u32)
// or
fn to_high_low(self) -> [u32; 2]
```

I think it's more natural to put the high bit first. Because the most significant bit is often on the left. Also, do you think it's better to return a tuple (`(u32, u32)`) or an array (`[u32; 2]`) for `to_high_low`?

**Comment by russellbanks** [comment]
> Also, do you think it's better to return a tuple (`(u32, u32)`) or an array (`[u32; 2]`) for `to_high_low`?

Returning a tuple because it can be destructured:

```rust
let (high, low) = filetime.to_high_low();
```

**Comment by sorairolake** [comment]
@russellbanks [Version  0.10.4](https://crates.io/crates/nt-time/0.10.4), which implemented this feature, was released on December 24th of last year. See the documentation for [`FileTime::to_high_low`](https://docs.rs/nt-time/0.10.4/nt_time/struct.FileTime.html#method.to_high_low) and [`FileTime::from_high_low`](https://docs.rs/nt-time/0.10.4/nt_time/struct.FileTime.html#method.from_high_low) for details.
