### ISSUE TITLE
FILETIME should be i64?

### ISSUE THREAD

**Issue by teohhanhui** [sorairolake/nt-time#58]
I could not find any explicit mention that it's an `i64`, but it's pretty strongly hinted:

* https://learn.microsoft.com/en-us/uwp/cpp-ref-for-winrt/clock
* https://learn.microsoft.com/en-us/windows/win32/adschema/a-accountexpires#remarks

And of course, Windows seems to represent it as 2 x `u32`, so who knows?
* https://learn.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-filetime
* https://learn.microsoft.com/en-us/windows/win32/winprog/windows-data-types#DWORD

**Comment by teohhanhui** [comment]
Oh, I think you're right that it's a `u64`:

From https://learn.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-filetime#remarks:
> It is not recommended that you add and subtract values from the FILETIME structure to obtain relative times. Instead, you should copy the low- and high-order parts of the file time to a [ULARGE_INTEGER](https://learn.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-ularge_integer-r1) structure, perform 64-bit arithmetic on the QuadPart member, and copy the LowPart and HighPart members into the FILETIME structure.

And [ULARGE_INTEGER](https://learn.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-ularge_integer-r1) represents a `u64`.

**Comment by teohhanhui** [comment]
Hmm... But actually in .NET it's an `Int64`:

* https://learn.microsoft.com/en-us/dotnet/api/system.datetime.fromfiletime?view=net-7.0
* https://learn.microsoft.com/en-us/dotnet/api/system.datetime.tofiletime?view=net-7.0

**Comment by sorairolake** [comment]
The prerequisites for `lpFileTime` parameters of [`FileTimeToSystemTime()`](https://learn.microsoft.com/en-us/windows/win32/api/timezoneapi/nf-timezoneapi-filetimetosystemtime) are as follows:

> This value must be less than 0x8000000000000000. Otherwise, the function fails.

`0x8000000000000000` is equivalent to `i64::MAX + 1`. From this and the definition of [`FILETIME`](https://learn.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-filetime),[^1] I think size of `FILETIME` is `u64`.

[^1]: This has two [`DWORD`](https://learn.microsoft.com/en-us/windows/win32/winprog/windows-data-types) (equivalent to `u32`) members.

**Comment by teohhanhui** [comment]
Again, I think you're probably right. The whole situation is a mess (lol Microsoft).

Thank you for investigating, and for your explanation.
